# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Go HelloWorld example"
  homepage ""
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.7/homebrew-helloworld_Darwin_x86_64.tar.gz"
      sha256 "019bcc8f82c1edd269962df5a28bd58066454722189df1408cf5bc9d95a21e88"

      def install
        bin.install "homebrew-helloworld"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.7/homebrew-helloworld_Darwin_arm64.tar.gz"
      sha256 "cfa79e8a30fadab95187a94503c4170d4c4c16943d425d1d48163215c919b6b0"

      def install
        bin.install "homebrew-helloworld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.7/homebrew-helloworld_Linux_x86_64.tar.gz"
        sha256 "db46357da6dbd7ce76836aef8ab604b7bb34dd9b0dc35f3d7a078139f71ae6fd"

        def install
          bin.install "homebrew-helloworld"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.7/homebrew-helloworld_Linux_arm64.tar.gz"
        sha256 "bbdf507ea0c288495d896abf67d8303fe3a61168c7addf37e0006850d220e423"

        def install
          bin.install "homebrew-helloworld"
        end
      end
    end
  end
end
