# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Go HelloWorld example"
  homepage ""
  version "0.1.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.10/hello_Darwin_x86_64.tar.gz"
      sha256 "6c7e656bf224e98410834cfa81d89d1a700b0f07e942fa1073b6ec0914141d41"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.10/hello_Darwin_arm64.tar.gz"
      sha256 "ba6e99817a43dfe15103d40ea7be3bf3c5259a7f6d933c7647894273177b4f23"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.10/hello_Linux_x86_64.tar.gz"
        sha256 "63674fd4880d86c2a22763238cf6b61c4c4fcdd03af10c47b048a4f8b10ad419"

        def install
          bin.install "hello"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ch007m/homebrew-helloworld/releases/download/v0.1.10/hello_Linux_arm64.tar.gz"
        sha256 "87009be890f5d9d0dcbdcf27316bc14aaf3c351d37a64d1a87746c01f241d800"

        def install
          bin.install "hello"
        end
      end
    end
  end
end
