# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idp2 < Formula
  desc "IDP Client to create kind cluster"
  homepage "https://cnoe.io/"
  version "0.8.1"

  on_macos do
    on_intel do
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-darwin-amd64.tar.gz"
      sha256 "64c0b81aa844aa3160e9c93d44eb17a5cdb0b7ff605eaff3467c94ebfd8c8f79"

      def install
        bin.install "idpbuilder"
      end
    end
    on_arm do
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-darwin-arm64.tar.gz"
      sha256 "39b885668f07a1156f55ad3cb6b4b06c0b4ed6ef363db8a8c966aeabb1e67ad3"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-linux-amd64.tar.gz"
        sha256 "03934727bfbf39b1e61a74d8e045796cda2de14f8ce4c01df27f43d4494021de"

        def install
          bin.install "idpbuilder"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-linux-arm64.tar.gz"
        sha256 "b890a7a212a3fc69e6ea4b2a29d59f80ed501a27ad654c819a155cc7c3c6aa8d"

        def install
          bin.install "idpbuilder"
        end
      end
    end
  end

  test do
    system "idpbuilder version"
  end
end
