# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpbuilder < Formula
  desc "IDP Client to create kind cluster"
  homepage "https://cnoe.io/"
  version "0.8.1"

  on_macos do
    on_intel do
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-darwin-amd64.tar.gz"
      sha256 "64c0b81aa844aa3160e9c93d44eb17a5cdb0b7ff605eaff3467c94ebfd8c8f79"

      def install
        bin.install "idpbuilder"
      end
    end
    on_arm do
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-darwin-arm64.tar.gz"
      sha256 "79192e9656d8d25e813d16179464095edcde13440490507a434ec97a318f1bae"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-linux-amd64.tar.gz"
        sha256 "03934727bfbf39b1e61a74d8e045796cda2de14f8ce4c01df27f43d4494021de"

        def install
          bin.install "idpbuilder"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.8.1/idpbuilder-linux-arm64.tar.gz"
        sha256 "ceaa2a3a62168cb67db4179e6fbf1c5b72d86fb0351ded85bf7032c4477ac5cf"

        def install
          bin.install "idpbuilder"
        end
      end
    end
  end

  test do
    system "idpbuilder version"
  end
end
