# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpbuilder < Formula
  desc "IDP Client to create kind cluster"
  homepage "https://cnoe.io/"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ch007m/homebrew-idpbuilder/releases/download/v0.1.6/homebrew-idpbuilder_Darwin_x86_64.tar.gz"
      sha256 "0d4ebf6aa566b1b9597d723e981a428b58b4a3e06499115e05d17288e06e2bf5"

      def install
        bin.install "homebrew-idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ch007m/homebrew-idpbuilder/releases/download/v0.1.6/homebrew-idpbuilder_Darwin_arm64.tar.gz"
      sha256 "acb345204076c54d0c63d3f92973aa905c9ad59683b2f669cdfab3caed656e13"

      def install
        bin.install "homebrew-idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ch007m/homebrew-idpbuilder/releases/download/v0.1.6/homebrew-idpbuilder_Linux_x86_64.tar.gz"
        sha256 "ee824d3a123288def02741a392ced7b4f36239db240f8b0139fa08c05f4039b2"

        def install
          bin.install "homebrew-idpbuilder"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ch007m/homebrew-idpbuilder/releases/download/v0.1.6/homebrew-idpbuilder_Linux_arm64.tar.gz"
        sha256 "9fcc1f8bb0646d06d959e19dac709f977afe46889fd597f02a43a339b6e2d8ac"

        def install
          bin.install "homebrew-idpbuilder"
        end
      end
    end
  end

  test do
    system "idpbuilder version"
  end
end
